
## STRUCTURAL

python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 10 --type_training AD --mini_batch 200 --learning_rate 0.01 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 50 --type_training AD --mini_batch 200 --learning_rate 0.001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 100 --type_training AD --mini_batch 200 --learning_rate 0.0001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 10 --type_training RB --mini_batch 200 --learning_rate 0.01 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 50 --type_training RB --mini_batch 200 --learning_rate 0.001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 100 --type_training RB --mini_batch 200 --learning_rate 0.0001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist


## UTILITY

python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 10 --type_training AD --mini_batch 200 --learning_rate 0.01 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 50 --type_training AD --mini_batch 200 --learning_rate 0.001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 100 --type_training AD --mini_batch 200 --learning_rate 0.0001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 10 --type_training RB --mini_batch 200 --learning_rate 0.01 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 50 --type_training RB --mini_batch 200 --learning_rate 0.001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 100 --type_training RB --mini_batch 200 --learning_rate 0.0001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 15 --y-length 5 --input_dim 2 --output_dim 1 --sampling_method Dist


## STRUCTURAL

python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 10 --type_training AD --mini_batch 200 --learning_rate 0.01 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 50 --type_training AD --mini_batch 200 --learning_rate 0.001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 100 --type_training AD --mini_batch 200 --learning_rate 0.0001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 10 --type_training RB --mini_batch 200 --learning_rate 0.01 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 50 --type_training RB --mini_batch 200 --learning_rate 0.001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 100 --type_training RB --mini_batch 200 --learning_rate 0.0001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Structural.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist


## UTILITY

python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 10 --type_training AD --mini_batch 200 --learning_rate 0.01 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 50 --type_training AD --mini_batch 200 --learning_rate 0.001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 100 --type_training AD --mini_batch 200 --learning_rate 0.0001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 10 --type_training RB --mini_batch 200 --learning_rate 0.01 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 50 --type_training RB --mini_batch 200 --learning_rate 0.001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
python model/pytorchRNN_unguidedPeriods_moreFeatures.py --epochs 100000 --hidden_layer 100 --type_training RB --mini_batch 200 --learning_rate 0.0001 --percentage 0.5 --type_rnn lstm --type_actifun sigmoid --data_path ./Data/MixedPeriods/Utility.csv --x-length 10 --y-length 3 --input_dim 2 --output_dim 1 --sampling_method Dist
